name: Publish Python Package

on:
  release:
    types: [published]
    tags:
      - "live-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        run: echo "PACKAGE_VERSION=$(echo ${GITHUB_REF#refs/tags/live-})" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install twine "betterproto[compiler]" betterproto grpcio grpcio-tools grpcio-tools

      - name: Generate gRPC Code (Ensure 'generated/' Exists)
        run: |
          mkdir -p generated  # Create directory if it doesn't exist
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=generated proto/*.proto

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

  generate-readme:
    runs-on: ubuntu-latest
    needs: deploy  # Ensures `deploy` completes first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Switch to Main Branch
        run: |
          git checkout main
          git pull origin main  # Ensure latest changes

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "betterproto[compiler]" betterproto grpcio grpcio-tools grpcio-tools pydoc-markdown

      - name: Generate gRPC Code (Ensure 'generated/' Exists)
        run: |
          mkdir -p generated
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=generated proto/*.proto
          touch generated/__init__.py  # Ensure it's a valid Python package
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$(pwd)/generated" >> $GITHUB_ENV

      - name: Debug - Check if 'generated' is Importable
        run: python -c "import generated; print('Generated module is importable!')"

      - name: Generate API Documentation as README.md
        run: |
          echo "# API Documentation" > README.md
          echo "" >> README.md
          echo "## Generated gRPC API" >> README.md
          echo '```python' >> README.md
          pydoc-markdown --module generated > tmp.md
          cat tmp.md | sed '/^ *$/d' >> README.md  # Remove empty lines
          echo '```' >> README.md
          rm tmp.md

      - name: Commit and Push README
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update README with BetterProto API documentation" || echo "No changes to commit"
          git push origin main
