name: Publish Python Package

on:
  release:
    types: [published]
    tags:
      - "live-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        run: echo "PACKAGE_VERSION=$(echo ${GITHUB_REF#refs/tags/live-})" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install twine "betterproto[compiler]" betterproto grpcio grpcio-tools

      - name: Create Package Directories
        run: |
          mkdir -p viuapi
          mkdir -p jinaembed

      - name: Generate gRPC Code
        run: |
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=viuapi proto/viu-api.proto
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=jinaembed proto/jinaembed.proto
          touch viuapi/__init__.py
          touch jinaembed/__init__.py

      - name: Move generated files to root and rename
        run: |
          mv viuapi/viuapi.py .
          mv viuapi/viuapi.pyi .  # Keep the .pyi file!
          mv jinaembed/jinaembed.py .
          mv jinaembed/jinaembed.pyi . # Keep the .pyi file!

      - name: Build package
        run: python setup.py sdist bdist_wheel  # Assuming you have a setup.py

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

  generate-readme:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch entire history

      - name: Switch to Main Branch (BEFORE ANYTHING ELSE)
        run: |
          git checkout main
          git pull origin main  # Get latest main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "betterproto[compiler]" betterproto grpcio grpcio-tools pydoc-markdown

      - name: Create Package Directories
        run: |
          mkdir -p viuapi
          mkdir -p jinaembed

      - name: Generate gRPC Code
        run: |
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=viuapi --pyi_out=viuapi proto/viu-api.proto
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=jinaembed --pyi_out=jinaembed proto/jinaembed.proto
          touch viuapi/__init__.py
          touch jinaembed/__init__.py

      - name: Move generated files to root and rename
        run: |
          mv viuapi/viuapi.py .
          mv viuapi/viuapi.pyi .
          mv jinaembed/jinaembed.py .
          mv jinaembed/jinaembed.pyi .

      - name: Set PYTHONPATH and PATH
        run: |
          echo "PYTHONPATH=.:$PYTHONPATH" >> $GITHUB_ENV
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Debug - List Files (BEFORE ANYTHING)
        run: ls -la

      - name: Debug PYTHONPATH and PATH
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          echo "PATH is: $PATH"

      - name: Debug - Check if 'generated' is Importable
        run: python -c "import viuapi; print('Generated module is importable!')"

      - name: Generate API Documentation as README.md
        run: |
          echo "# API Documentation" > README.md
          echo "" >> README.md
          echo "## Generated gRPC API" >> README.md
          pydoc-markdown --module viuapi --render-toc > tmp.md
          cat tmp.md | sed '/^ *$/d' >> README.md  # Add content to README.md
          rm tmp.md

      - name: Clean Up (AGGRESSIVE!)
        run: rm -rf viuapi jinaembed viuapi.py jinaembed.py

      - name: Debug - List Files (AFTER DOC GEN)
        run: ls -la

      - name: Debug - Show README Content
        run: cat README.md

      - name: Debug - Git Status (Before Commit)
        run: git status

      - name: Commit and Push README
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .  # Add *ALL* changes, including the README
          git commit -m "Auto-update README with BetterProto API documentation" || echo "No changes to commit"
          git push origin main

      - name: Debug - Git Status (After Commit)
        run: git status
