name: Publish Python Package

on:
  release:
    types: [published]
    tags:
      - "live-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        run: echo "PACKAGE_VERSION=$(echo ${GITHUB_REF#refs/tags/live-})" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install twine "betterproto[compiler]" betterproto grpcio grpcio-tools

      - name: Create Package Directories
        run: |
          mkdir -p viuapi
          mkdir -p jinaembed

      - name: Generate gRPC Code
        run: |
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=viuapi proto/viu-api.proto
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=jinaembed proto/jinaembed.proto
          touch viuapi/__init__.py
          touch jinaembed/__init__.py

      - name: Move generated files to root and rename
        run: |
          mv viuapi/viuapi.py .
          mv jinaembed/jinaembed.py .

      - name: Build package
        run: python setup.py sdist bdist_wheel  # Assuming you have a setup.py

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

  generate-readme:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to Main Branch
        run: |
          git checkout main
          git pull origin main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "betterproto[compiler]" betterproto grpcio grpcio-tools pydoc-markdown

      - name: Create Package Directories
        run: |
          mkdir -p viuapi
          mkdir -p jinaembed

      - name: Generate gRPC Code
        run: |
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=viuapi proto/viu-api.proto
          python -m grpc_tools.protoc -Iproto --python_betterproto_out=jinaembed proto/jinaembed.proto
          touch viuapi/__init__.py
          touch jinaembed/__init__.py

      - name: Move generated files to root
        run: |
          mv viuapi/viuapi.py .
          mv jinaembed/jinaembed.py .

      - name: List Files (Debugging)
        run: ls -la

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=.:$PYTHONPATH" >> $GITHUB_ENV

      - name: Debug PYTHONPATH
        run: echo "PYTHONPATH is: $PYTHONPATH"

      - name: Debug - Check if 'generated' is Importable
        run: python -c "import viuapi; print('Generated module is importable!')"

      - name: Generate API Documentation as README.md
        run: |
          echo "# API Documentation" > README.md
          echo "" >> README.md
          echo "## Generated gRPC API" >> README.md
          python -m pydoc_markdown --module viuapi --render-toc > tmp.md  # Use python -m
          cat tmp.md | sed '/^ *$/d' >> README.md
          rm tmp.md

      - name: Commit and Push README
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update README with BetterProto API documentation" || echo "No changes to commit"
          git push origin main
